CREATE TABLE DAT_DEVICE (Id BIGSERIAL NOT NULL, NUM_UID int8 NOT NULL UNIQUE, FK_GATEWAY int8 NOT NULL, DES_VENDOR varchar(100) NOT NULL, FLG_STATUS int4 NOT NULL, PRIMARY KEY (Id));
CREATE TABLE DAT_GATEWAY (Id BIGSERIAL NOT NULL, DES_SERIAL_NUMBER varchar(50) NOT NULL UNIQUE, DES_NAME varchar(50) NOT NULL, DES_IPV4 varchar(20) NOT NULL, PRIMARY KEY (Id));
ALTER TABLE DAT_DEVICE ADD CONSTRAINT FKDAT_DEVICE984729 FOREIGN KEY (FK_GATEWAY) REFERENCES DAT_GATEWAY (Id);

